apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.datalust.co
    chart: seq
    targetRevision: 2023.4.0 # Replace with desired version
    helm:
      valueFiles:
        - values.yaml # Ensure this is relative to the repository's root
  destination:
    server: https://kubernetes.default.svc
    namespace: seq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
